version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./manage.py test
          name: Test
  beagle-trigger:
    docker:
        - image: beaglesecurity/beagle-test-trigger-common:latest
    steps:
        - run:
            command: trigger-test

workflows:
  main:
    jobs:
      - build-and-test
      - beagle-trigger
