version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./manage.py test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
machine:
  post:
    - cp -r /usr/local/bin/git $HOME/git
dependencies:
  cache_directories:
    - $HOME/git
  post:
    - sudo cp -r $HOME/git /usr/local/bin/git